spring:
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  mvc:
    path match:
      matching-strategy: ant_path_matcher

jwt:
  secret: ${JWT_SECRET}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  springframework.web: DEBUG
  springframework.security: DEBUG
