spring:
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  secret: ${JWT_SECRET}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  springframework.web: DEBUG
  springframework.security: DEBUG
